name: Update

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: winget-jr

      - name: Checkout macports fork
        uses: actions/checkout@v3
        with:
          repository: jvalkeal/winget-pkgs
          path: winget-pkgs
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}

      - name: Refresh fork
        run: |
          cd winget-pkgs
          git remote add upstream https://github.com/microsoft/winget-pkgs.git
          git pull upstream master

      - name: Branch update
        run: |
          BRANCH=spring-cli-installer-${{ github.ref_name }}
          VERSION=${BRANCH#v}
          cd winget-pkgs
          git checkout -b $BRANCH
          mkdir -p manifests/s/Spring/spring-cli
          cp -R ../winget-jr/s/Spring/spring-cli/$VERSION manifests/s/Spring/spring-cli
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -a -m "spring-cli-installer: update to version ${{ github.ref_name }}"
          git push origin $BRANCH
